/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralRouteImport } from './routes/_central'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as CentralAuditoriaRouteImport } from './routes/_central.auditoria'
import { Route as CentralCentralRouteImport } from './routes/_central.central'
import { Route as CentralConfiguracoesRouteImport } from './routes/_central.configuracoes'
import { Route as CentralEquipeRouteImport } from './routes/_central.equipe'
import { Route as CentralEscalasRouteImport } from './routes/_central.escalas'
import { Route as CentralEvidenciasRouteImport } from './routes/_central.evidencias'
import { Route as CentralMonitoramentoRouteImport } from './routes/_central.monitoramento'
import { Route as CentralRelatoriosRouteImport } from './routes/_central.relatorios'
import { Route as CentralSaudeDoSistemaRouteImport } from './routes/_central.saude-do-sistema'
import { Route as CentralVeiculosRouteImport } from './routes/_central.veiculos'
import { Route as CentralAlertasIndexRouteImport } from './routes/_central.alertas.index'
import { Route as CentralAlertasAlertIdRouteImport } from './routes/_central.alertas.$alertId'
import { Route as CentralEquipeCargosPermissoesRouteImport } from './routes/_central.equipe.cargos-permissoes'
import { Route as CentralEquipeNovoRouteImport } from './routes/_central.equipe.novo'
import { Route as CentralHistoricoAlertasRouteImport } from './routes/_central.historico.alertas'
import { Route as CentralMotoristasIndexRouteImport } from './routes/_central.motoristas.index'
import { Route as CentralMotoristasDriverIdRouteImport } from './routes/_central.motoristas.$driverId'
import { Route as CentralSessoesSessionIdRouteImport } from './routes/_central.sessoes.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/_central',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAuditoriaRoute = CentralAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => CentralRoute,
} as any)
const CentralCentralRoute = CentralCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => CentralRoute,
} as any)
const CentralConfiguracoesRoute = CentralConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => CentralRoute,
} as any)
const CentralEquipeRoute = CentralEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => CentralRoute,
} as any)
const CentralEscalasRoute = CentralEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => CentralRoute,
} as any)
const CentralEvidenciasRoute = CentralEvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMonitoramentoRoute = CentralMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => CentralRoute,
} as any)
const CentralRelatoriosRoute = CentralRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CentralRoute,
} as any)
const CentralSaudeDoSistemaRoute = CentralSaudeDoSistemaRouteImport.update({
  id: '/saude-do-sistema',
  path: '/saude-do-sistema',
  getParentRoute: () => CentralRoute,
} as any)
const CentralVeiculosRoute = CentralVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => CentralRoute,
} as any)
const CentralAlertasIndexRoute = CentralAlertasIndexRouteImport.update({
  id: '/alertas/',
  path: '/alertas/',
  getParentRoute: () => CentralRoute,
} as any)
const CentralAlertasAlertIdRoute = CentralAlertasAlertIdRouteImport.update({
  id: '/alertas/$alertId',
  path: '/alertas/$alertId',
  getParentRoute: () => CentralRoute,
} as any)
const CentralEquipeCargosPermissoesRoute =
  CentralEquipeCargosPermissoesRouteImport.update({
    id: '/cargos-permissoes',
    path: '/cargos-permissoes',
    getParentRoute: () => CentralEquipeRoute,
  } as any)
const CentralEquipeNovoRoute = CentralEquipeNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => CentralEquipeRoute,
} as any)
const CentralHistoricoAlertasRoute = CentralHistoricoAlertasRouteImport.update({
  id: '/historico/alertas',
  path: '/historico/alertas',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMotoristasIndexRoute = CentralMotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMotoristasDriverIdRoute =
  CentralMotoristasDriverIdRouteImport.update({
    id: '/motoristas/$driverId',
    path: '/motoristas/$driverId',
    getParentRoute: () => CentralRoute,
  } as any)
const CentralSessoesSessionIdRoute = CentralSessoesSessionIdRouteImport.update({
  id: '/sessoes/$sessionId',
  path: '/sessoes/$sessionId',
  getParentRoute: () => CentralRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/auditoria': typeof CentralAuditoriaRoute
  '/central': typeof CentralCentralRoute
  '/configuracoes': typeof CentralConfiguracoesRoute
  '/equipe': typeof CentralEquipeRouteWithChildren
  '/escalas': typeof CentralEscalasRoute
  '/evidencias': typeof CentralEvidenciasRoute
  '/monitoramento': typeof CentralMonitoramentoRoute
  '/relatorios': typeof CentralRelatoriosRoute
  '/saude-do-sistema': typeof CentralSaudeDoSistemaRoute
  '/veiculos': typeof CentralVeiculosRoute
  '/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/equipe/cargos-permissoes': typeof CentralEquipeCargosPermissoesRoute
  '/equipe/novo': typeof CentralEquipeNovoRoute
  '/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/alertas/': typeof CentralAlertasIndexRoute
  '/motoristas/': typeof CentralMotoristasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/auditoria': typeof CentralAuditoriaRoute
  '/central': typeof CentralCentralRoute
  '/configuracoes': typeof CentralConfiguracoesRoute
  '/equipe': typeof CentralEquipeRouteWithChildren
  '/escalas': typeof CentralEscalasRoute
  '/evidencias': typeof CentralEvidenciasRoute
  '/monitoramento': typeof CentralMonitoramentoRoute
  '/relatorios': typeof CentralRelatoriosRoute
  '/saude-do-sistema': typeof CentralSaudeDoSistemaRoute
  '/veiculos': typeof CentralVeiculosRoute
  '/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/equipe/cargos-permissoes': typeof CentralEquipeCargosPermissoesRoute
  '/equipe/novo': typeof CentralEquipeNovoRoute
  '/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/alertas': typeof CentralAlertasIndexRoute
  '/motoristas': typeof CentralMotoristasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_central': typeof CentralRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/_central/auditoria': typeof CentralAuditoriaRoute
  '/_central/central': typeof CentralCentralRoute
  '/_central/configuracoes': typeof CentralConfiguracoesRoute
  '/_central/equipe': typeof CentralEquipeRouteWithChildren
  '/_central/escalas': typeof CentralEscalasRoute
  '/_central/evidencias': typeof CentralEvidenciasRoute
  '/_central/monitoramento': typeof CentralMonitoramentoRoute
  '/_central/relatorios': typeof CentralRelatoriosRoute
  '/_central/saude-do-sistema': typeof CentralSaudeDoSistemaRoute
  '/_central/veiculos': typeof CentralVeiculosRoute
  '/_central/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/_central/equipe/cargos-permissoes': typeof CentralEquipeCargosPermissoesRoute
  '/_central/equipe/novo': typeof CentralEquipeNovoRoute
  '/_central/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/_central/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/_central/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/_central/alertas/': typeof CentralAlertasIndexRoute
  '/_central/motoristas/': typeof CentralMotoristasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/auditoria'
    | '/central'
    | '/configuracoes'
    | '/equipe'
    | '/escalas'
    | '/evidencias'
    | '/monitoramento'
    | '/relatorios'
    | '/saude-do-sistema'
    | '/veiculos'
    | '/alertas/$alertId'
    | '/equipe/cargos-permissoes'
    | '/equipe/novo'
    | '/historico/alertas'
    | '/motoristas/$driverId'
    | '/sessoes/$sessionId'
    | '/alertas/'
    | '/motoristas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/auditoria'
    | '/central'
    | '/configuracoes'
    | '/equipe'
    | '/escalas'
    | '/evidencias'
    | '/monitoramento'
    | '/relatorios'
    | '/saude-do-sistema'
    | '/veiculos'
    | '/alertas/$alertId'
    | '/equipe/cargos-permissoes'
    | '/equipe/novo'
    | '/historico/alertas'
    | '/motoristas/$driverId'
    | '/sessoes/$sessionId'
    | '/alertas'
    | '/motoristas'
  id:
    | '__root__'
    | '/'
    | '/_central'
    | '/login'
    | '/primeiro-acesso'
    | '/_central/auditoria'
    | '/_central/central'
    | '/_central/configuracoes'
    | '/_central/equipe'
    | '/_central/escalas'
    | '/_central/evidencias'
    | '/_central/monitoramento'
    | '/_central/relatorios'
    | '/_central/saude-do-sistema'
    | '/_central/veiculos'
    | '/_central/alertas/$alertId'
    | '/_central/equipe/cargos-permissoes'
    | '/_central/equipe/novo'
    | '/_central/historico/alertas'
    | '/_central/motoristas/$driverId'
    | '/_central/sessoes/$sessionId'
    | '/_central/alertas/'
    | '/_central/motoristas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralRoute: typeof CentralRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central': {
      id: '/_central'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central/auditoria': {
      id: '/_central/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof CentralAuditoriaRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/central': {
      id: '/_central/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralCentralRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/configuracoes': {
      id: '/_central/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof CentralConfiguracoesRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/equipe': {
      id: '/_central/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof CentralEquipeRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/escalas': {
      id: '/_central/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof CentralEscalasRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/evidencias': {
      id: '/_central/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof CentralEvidenciasRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/monitoramento': {
      id: '/_central/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof CentralMonitoramentoRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/relatorios': {
      id: '/_central/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof CentralRelatoriosRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/saude-do-sistema': {
      id: '/_central/saude-do-sistema'
      path: '/saude-do-sistema'
      fullPath: '/saude-do-sistema'
      preLoaderRoute: typeof CentralSaudeDoSistemaRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/veiculos': {
      id: '/_central/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof CentralVeiculosRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/alertas/': {
      id: '/_central/alertas/'
      path: '/alertas'
      fullPath: '/alertas/'
      preLoaderRoute: typeof CentralAlertasIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/alertas/$alertId': {
      id: '/_central/alertas/$alertId'
      path: '/alertas/$alertId'
      fullPath: '/alertas/$alertId'
      preLoaderRoute: typeof CentralAlertasAlertIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/equipe/cargos-permissoes': {
      id: '/_central/equipe/cargos-permissoes'
      path: '/cargos-permissoes'
      fullPath: '/equipe/cargos-permissoes'
      preLoaderRoute: typeof CentralEquipeCargosPermissoesRouteImport
      parentRoute: typeof CentralEquipeRoute
    }
    '/_central/equipe/novo': {
      id: '/_central/equipe/novo'
      path: '/novo'
      fullPath: '/equipe/novo'
      preLoaderRoute: typeof CentralEquipeNovoRouteImport
      parentRoute: typeof CentralEquipeRoute
    }
    '/_central/historico/alertas': {
      id: '/_central/historico/alertas'
      path: '/historico/alertas'
      fullPath: '/historico/alertas'
      preLoaderRoute: typeof CentralHistoricoAlertasRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/motoristas/': {
      id: '/_central/motoristas/'
      path: '/motoristas'
      fullPath: '/motoristas/'
      preLoaderRoute: typeof CentralMotoristasIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/motoristas/$driverId': {
      id: '/_central/motoristas/$driverId'
      path: '/motoristas/$driverId'
      fullPath: '/motoristas/$driverId'
      preLoaderRoute: typeof CentralMotoristasDriverIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/sessoes/$sessionId': {
      id: '/_central/sessoes/$sessionId'
      path: '/sessoes/$sessionId'
      fullPath: '/sessoes/$sessionId'
      preLoaderRoute: typeof CentralSessoesSessionIdRouteImport
      parentRoute: typeof CentralRoute
    }
  }
}

interface CentralEquipeRouteChildren {
  CentralEquipeCargosPermissoesRoute: typeof CentralEquipeCargosPermissoesRoute
  CentralEquipeNovoRoute: typeof CentralEquipeNovoRoute
}

const CentralEquipeRouteChildren: CentralEquipeRouteChildren = {
  CentralEquipeCargosPermissoesRoute: CentralEquipeCargosPermissoesRoute,
  CentralEquipeNovoRoute: CentralEquipeNovoRoute,
}

const CentralEquipeRouteWithChildren = CentralEquipeRoute._addFileChildren(
  CentralEquipeRouteChildren,
)

interface CentralRouteChildren {
  CentralAuditoriaRoute: typeof CentralAuditoriaRoute
  CentralCentralRoute: typeof CentralCentralRoute
  CentralConfiguracoesRoute: typeof CentralConfiguracoesRoute
  CentralEquipeRoute: typeof CentralEquipeRouteWithChildren
  CentralEscalasRoute: typeof CentralEscalasRoute
  CentralEvidenciasRoute: typeof CentralEvidenciasRoute
  CentralMonitoramentoRoute: typeof CentralMonitoramentoRoute
  CentralRelatoriosRoute: typeof CentralRelatoriosRoute
  CentralSaudeDoSistemaRoute: typeof CentralSaudeDoSistemaRoute
  CentralVeiculosRoute: typeof CentralVeiculosRoute
  CentralAlertasAlertIdRoute: typeof CentralAlertasAlertIdRoute
  CentralHistoricoAlertasRoute: typeof CentralHistoricoAlertasRoute
  CentralMotoristasDriverIdRoute: typeof CentralMotoristasDriverIdRoute
  CentralSessoesSessionIdRoute: typeof CentralSessoesSessionIdRoute
  CentralAlertasIndexRoute: typeof CentralAlertasIndexRoute
  CentralMotoristasIndexRoute: typeof CentralMotoristasIndexRoute
}

const CentralRouteChildren: CentralRouteChildren = {
  CentralAuditoriaRoute: CentralAuditoriaRoute,
  CentralCentralRoute: CentralCentralRoute,
  CentralConfiguracoesRoute: CentralConfiguracoesRoute,
  CentralEquipeRoute: CentralEquipeRouteWithChildren,
  CentralEscalasRoute: CentralEscalasRoute,
  CentralEvidenciasRoute: CentralEvidenciasRoute,
  CentralMonitoramentoRoute: CentralMonitoramentoRoute,
  CentralRelatoriosRoute: CentralRelatoriosRoute,
  CentralSaudeDoSistemaRoute: CentralSaudeDoSistemaRoute,
  CentralVeiculosRoute: CentralVeiculosRoute,
  CentralAlertasAlertIdRoute: CentralAlertasAlertIdRoute,
  CentralHistoricoAlertasRoute: CentralHistoricoAlertasRoute,
  CentralMotoristasDriverIdRoute: CentralMotoristasDriverIdRoute,
  CentralSessoesSessionIdRoute: CentralSessoesSessionIdRoute,
  CentralAlertasIndexRoute: CentralAlertasIndexRoute,
  CentralMotoristasIndexRoute: CentralMotoristasIndexRoute,
}

const CentralRouteWithChildren =
  CentralRoute._addFileChildren(CentralRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralRoute: CentralRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
