/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralRouteImport } from './routes/_central'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as CentralCentralRouteImport } from './routes/_central.central'
import { Route as CentralMonitoramentoRouteImport } from './routes/_central.monitoramento'
import { Route as CentralAlertasIndexRouteImport } from './routes/_central.alertas.index'
import { Route as CentralAlertasAlertIdRouteImport } from './routes/_central.alertas.$alertId'
import { Route as CentralHistoricoAlertasRouteImport } from './routes/_central.historico.alertas'
import { Route as CentralMotoristasIndexRouteImport } from './routes/_central.motoristas.index'
import { Route as CentralMotoristasDriverIdRouteImport } from './routes/_central.motoristas.$driverId'
import { Route as CentralSessoesSessionIdRouteImport } from './routes/_central.sessoes.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/_central',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralCentralRoute = CentralCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMonitoramentoRoute = CentralMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => CentralRoute,
} as any)
const CentralAlertasIndexRoute = CentralAlertasIndexRouteImport.update({
  id: '/alertas/',
  path: '/alertas/',
  getParentRoute: () => CentralRoute,
} as any)
const CentralAlertasAlertIdRoute = CentralAlertasAlertIdRouteImport.update({
  id: '/alertas/$alertId',
  path: '/alertas/$alertId',
  getParentRoute: () => CentralRoute,
} as any)
const CentralHistoricoAlertasRoute = CentralHistoricoAlertasRouteImport.update({
  id: '/historico/alertas',
  path: '/historico/alertas',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMotoristasIndexRoute = CentralMotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => CentralRoute,
} as any)
const CentralMotoristasDriverIdRoute =
  CentralMotoristasDriverIdRouteImport.update({
    id: '/motoristas/$driverId',
    path: '/motoristas/$driverId',
    getParentRoute: () => CentralRoute,
  } as any)
const CentralSessoesSessionIdRoute = CentralSessoesSessionIdRouteImport.update({
  id: '/sessoes/$sessionId',
  path: '/sessoes/$sessionId',
  getParentRoute: () => CentralRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/central': typeof CentralCentralRoute
  '/monitoramento': typeof CentralMonitoramentoRoute
  '/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/alertas/': typeof CentralAlertasIndexRoute
  '/motoristas/': typeof CentralMotoristasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/central': typeof CentralCentralRoute
  '/monitoramento': typeof CentralMonitoramentoRoute
  '/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/alertas': typeof CentralAlertasIndexRoute
  '/motoristas': typeof CentralMotoristasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_central': typeof CentralRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/_central/central': typeof CentralCentralRoute
  '/_central/monitoramento': typeof CentralMonitoramentoRoute
  '/_central/alertas/$alertId': typeof CentralAlertasAlertIdRoute
  '/_central/historico/alertas': typeof CentralHistoricoAlertasRoute
  '/_central/motoristas/$driverId': typeof CentralMotoristasDriverIdRoute
  '/_central/sessoes/$sessionId': typeof CentralSessoesSessionIdRoute
  '/_central/alertas/': typeof CentralAlertasIndexRoute
  '/_central/motoristas/': typeof CentralMotoristasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/central'
    | '/monitoramento'
    | '/alertas/$alertId'
    | '/historico/alertas'
    | '/motoristas/$driverId'
    | '/sessoes/$sessionId'
    | '/alertas/'
    | '/motoristas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/central'
    | '/monitoramento'
    | '/alertas/$alertId'
    | '/historico/alertas'
    | '/motoristas/$driverId'
    | '/sessoes/$sessionId'
    | '/alertas'
    | '/motoristas'
  id:
    | '__root__'
    | '/'
    | '/_central'
    | '/login'
    | '/primeiro-acesso'
    | '/_central/central'
    | '/_central/monitoramento'
    | '/_central/alertas/$alertId'
    | '/_central/historico/alertas'
    | '/_central/motoristas/$driverId'
    | '/_central/sessoes/$sessionId'
    | '/_central/alertas/'
    | '/_central/motoristas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralRoute: typeof CentralRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central': {
      id: '/_central'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central/central': {
      id: '/_central/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralCentralRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/monitoramento': {
      id: '/_central/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof CentralMonitoramentoRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/alertas/': {
      id: '/_central/alertas/'
      path: '/alertas'
      fullPath: '/alertas/'
      preLoaderRoute: typeof CentralAlertasIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/alertas/$alertId': {
      id: '/_central/alertas/$alertId'
      path: '/alertas/$alertId'
      fullPath: '/alertas/$alertId'
      preLoaderRoute: typeof CentralAlertasAlertIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/historico/alertas': {
      id: '/_central/historico/alertas'
      path: '/historico/alertas'
      fullPath: '/historico/alertas'
      preLoaderRoute: typeof CentralHistoricoAlertasRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/motoristas/': {
      id: '/_central/motoristas/'
      path: '/motoristas'
      fullPath: '/motoristas/'
      preLoaderRoute: typeof CentralMotoristasIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/motoristas/$driverId': {
      id: '/_central/motoristas/$driverId'
      path: '/motoristas/$driverId'
      fullPath: '/motoristas/$driverId'
      preLoaderRoute: typeof CentralMotoristasDriverIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_central/sessoes/$sessionId': {
      id: '/_central/sessoes/$sessionId'
      path: '/sessoes/$sessionId'
      fullPath: '/sessoes/$sessionId'
      preLoaderRoute: typeof CentralSessoesSessionIdRouteImport
      parentRoute: typeof CentralRoute
    }
  }
}

interface CentralRouteChildren {
  CentralCentralRoute: typeof CentralCentralRoute
  CentralMonitoramentoRoute: typeof CentralMonitoramentoRoute
  CentralAlertasAlertIdRoute: typeof CentralAlertasAlertIdRoute
  CentralHistoricoAlertasRoute: typeof CentralHistoricoAlertasRoute
  CentralMotoristasDriverIdRoute: typeof CentralMotoristasDriverIdRoute
  CentralSessoesSessionIdRoute: typeof CentralSessoesSessionIdRoute
  CentralAlertasIndexRoute: typeof CentralAlertasIndexRoute
  CentralMotoristasIndexRoute: typeof CentralMotoristasIndexRoute
}

const CentralRouteChildren: CentralRouteChildren = {
  CentralCentralRoute: CentralCentralRoute,
  CentralMonitoramentoRoute: CentralMonitoramentoRoute,
  CentralAlertasAlertIdRoute: CentralAlertasAlertIdRoute,
  CentralHistoricoAlertasRoute: CentralHistoricoAlertasRoute,
  CentralMotoristasDriverIdRoute: CentralMotoristasDriverIdRoute,
  CentralSessoesSessionIdRoute: CentralSessoesSessionIdRoute,
  CentralAlertasIndexRoute: CentralAlertasIndexRoute,
  CentralMotoristasIndexRoute: CentralMotoristasIndexRoute,
}

const CentralRouteWithChildren =
  CentralRoute._addFileChildren(CentralRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralRoute: CentralRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
